import { analyzeCoherence, assessFragmentation, buildCoherenceGraph, calculateContradictionDensity, calculateIntegrationCost, detectVerdictAttractors } from '../../shared/coherence';

describe('observable coherence geometry', () => {
  const coherent = buildCoherenceGraph({ claims: [{ id: 'c1' }, { id: 'c2' }], evidence: [{ id: 'e1' }, { id: 'e2' }], relations: [{ claim_id: 'c1', evidence_id: 'e1', relation_type: 'supports' }, { claim_id: 'c2', evidence_id: 'e2', relation_type: 'supports' }, { claim_id: 'c1', evidence_id: 'c2', relation_type: 'depends_on' }] });
  it('finds coherent connected claims deterministically', () => { expect(assessFragmentation(coherent).fragmented).toBe(false); expect(calculateContradictionDensity(coherent)).toBe(0); });
  it('measures direct contradictions without treating them as truth', () => { const graph = buildCoherenceGraph({ claims: [{ id: 'c1' }, { id: 'c2' }], contradictions: [{ claim_a_id: 'c1', claim_b_id: 'c2' }] }); expect(calculateContradictionDensity(graph)).toBe(1); expect(analyzeCoherence({ claims: [{ id: 'c1' }, { id: 'c2' }], contradictions: [{ claim_a_id: 'c1', claim_b_id: 'c2' }] }).warnings).toEqual([]); });
  it('reports disconnected and unsupported cross-cluster structure', () => { const graph = buildCoherenceGraph({ claims: [{ id: 'c1' }, { id: 'c2' }], evidence: [{ id: 'e1' }, { id: 'e2' }] }); const assessment = analyzeCoherence({ claims: [{ id: 'c1' }, { id: 'c2' }], evidence: [{ id: 'e1' }, { id: 'e2' }] }); expect(assessFragmentation(graph).cluster_count).toBe(4); expect(assessment.warnings).toContain('Answer combines weakly connected evidence clusters'); });
  it('bounds observable integration cost and flags overload', () => { expect(calculateIntegrationCost(coherent)).toBeGreaterThanOrEqual(0); expect(calculateIntegrationCost(coherent)).toBeLessThanOrEqual(1); expect(analyzeCoherence({ claims: Array.from({ length: 16 }, (_, i) => ({ id: `c${i}` })) }, { integration_budget: .2 }).integration.overloaded).toBe(true); });
  it('reports convergence as stability rather than evidence', () => { const attractors = detectVerdictAttractors([{ strategy: 'direct', verdict: 'supported', evidence_coverage: 0 }, { strategy: 'reordered', verdict: 'supported', evidence_coverage: 0 }, { strategy: 'critique', verdict: 'unsupported', evidence_coverage: 0 }]); expect(attractors[0]).toMatchObject({ normalized_verdict: 'supported', convergence_ratio: 2 / 3, evidence_consistency: 0 }); });
});
