import { describe, expect, it } from '@jest/globals';
import { validateEducationRequest } from '../../shared/education/schemas';
import { defaultEducationVerdictPolicy } from '../../shared/education/policy';
import { extractAtomicClaims, classifyClaim, classifyEvidenceRelations, calculateMetrics, verifyEducation } from '../src/services/educationVerification';

const science = { prompt: 'Explain why seasons occur.', aiResponse: "Earth's axial tilt causes seasons. Seasons occur because Earth is closer to the Sun in summer.", subject: 'science' as const, gradeLevel: 'high-school' as const, verificationMode: 'instructional' as const };
describe('education verification mode', () => {
  it('validates the focused API contract', () => { expect(validateEducationRequest(science).errors).toEqual([]); expect(validateEducationRequest({ ...science, aiResponse: '' }).errors[0].field).toBe('aiResponse'); });
  it('extracts atomic claims and distinguishes factual, interpretive, and normative statements', () => { expect(extractAtomicClaims(science.aiResponse, 'r')).toHaveLength(2); expect(classifyClaim('The evidence shows this was significant.').claimType).toBe('interpretive'); expect(classifyClaim('Nuclear energy should be expanded.').claimType).toBe('normative'); });
  it('classifies fixture evidence relationships, including a contradiction', () => { const claim = extractAtomicClaims(science.aiResponse, 'r')[1]; expect(classifyEvidenceRelations(claim, 'science')[0]).toMatchObject({ relation: 'contradicts', independenceCluster: 'astronomy-primary' }); });
  it('keeps duplicated provenance out of source independence calculations', () => { const claim = extractAtomicClaims('Earth\'s axial tilt causes seasons.', 'r')[0]; const relation = classifyEvidenceRelations(claim, 'science')[0]; const metrics = calculateMetrics(claim, [relation, { ...relation, evidenceId: 'reprint', relation: 'duplicates' }]); expect(metrics.sourceIndependence).toBe(1); });
  it('assigns contradicted, interpretation-dependent, and unable-to-verify outcomes distinctly', () => { const report = verifyEducation(science).report; expect(report.claims[1].assessment.status).toBe('contradicted'); expect(verifyEducation({ ...science, subject: 'history', aiResponse: 'The fall of Rome was significant.' }).report.claims[0].assessment.status).toBe('interpretation_dependent'); expect(verifyEducation({ ...science, subject: 'civics', aiResponse: 'Nuclear energy should be expanded.' }).report.claims[0].assessment.status).toBe('unable_to_verify'); });
  it('uses documented versioned policy thresholds', () => { const claim = extractAtomicClaims("Earth's axial tilt causes seasons.", 'r')[0]; expect(defaultEducationVerdictPolicy.evaluate({ ...calculateMetrics(claim, []), evidenceCoverage: 1, supportRatio: .9, sourceIndependence: 1 }, claim, [{ claimId: claim.id, evidenceId: 'e', relation: 'supports', explanation: 'x' }])).toBe('supported'); });
  it('serializes a deterministic portable receipt and report', () => { const first = verifyEducation(science); const second = verifyEducation(science); expect(first.receipt).toEqual(second.receipt); expect(first.receipt).toMatchObject({ output_hash: expect.any(String), receipt_hash: expect.any(String) }); expect(first.report.integrity.claimSetHash).toBeTruthy(); });
  it('keeps reports request-local for tenant-safe callers', () => { const a = verifyEducation(science); const b = verifyEducation({ ...science, aiResponse: 'Earth\'s axial tilt causes seasons.' }); expect(a.reportId).not.toBe(b.reportId); expect(a.report.claims).toHaveLength(2); });
  it('generates deterministic fixture reports for history, science, and civics', () => { expect(verifyEducation({ ...science, subject: 'history', prompt: 'What caused the fall of the Roman Empire?', aiResponse: 'The Roman Empire faced multiple interacting pressures. Lead poisoning was the primary cause.' }).report.summary.totalClaims).toBe(2); expect(verifyEducation(science).overallStatus).toBe('mixed_evidence'); expect(verifyEducation({ ...science, subject: 'civics', prompt: 'Should nuclear energy be expanded?', aiResponse: 'Nuclear energy should be expanded.' }).claims[0].claim.claimType).toBe('normative'); });
});
