import { describe, expect, it } from '@jest/globals';
import { validateEducationRequest } from '../../shared/education/schemas';
import { aggregateClaims, supportLevelForEvidence } from '../../shared/education/scoring';
import { verifyEducation } from '../src/services/educationVerification';
const request = { mode: 'student_answer' as const, question: 'Why?', content: "Earth's axial tilt causes seasons.", subject: 'earth-science', education_level: 'middle-school' as const, content_type: 'answer', privacy_acknowledged: true as const };
describe('education MVP', () => {
 it('validates request and requires privacy acknowledgement', () => { expect(validateEducationRequest(request).errors).toEqual([]); expect(validateEducationRequest({ ...request, privacy_acknowledged: false }).errors[0].field).toBe('privacy_acknowledged'); });
 it('applies documented evidence verdict thresholds and precedence', () => { expect(supportLevelForEvidence({ supportedClaimRatio: .95, contradictedClaimRatio: 0, evidenceCoverage: .8, independentSupportCount: 2, hasMaterialContradiction: false })).toBe('Supported'); expect(supportLevelForEvidence({ supportedClaimRatio: .95, contradictedClaimRatio: .1, evidenceCoverage: .8, independentSupportCount: 2, hasMaterialContradiction: true })).toBe('Mixed evidence'); expect(supportLevelForEvidence({ supportedClaimRatio: 1, contradictedClaimRatio: 0, evidenceCoverage: .4, independentSupportCount: 2, hasMaterialContradiction: false })).toBe('Unable to verify'); });
 it('returns deterministic ephemeral receipt and citation warning', () => { const first = verifyEducation({ ...request, content: 'Earth is flat. See https://example.com.' }); const second = verifyEducation({ ...request, content: 'Earth is flat. See https://example.com.' }); expect(first.task_id).toBe(second.task_id); expect(first.receipt.education.raw_content_persisted).toBe(false); expect(first.education_result.citation_review.warnings).not.toHaveLength(0); });
 it('exposes independent verification dimensions rather than relying on model consensus', () => { const result = verifyEducation(request); const dimensions = result.education_result.verification_dimensions; expect(dimensions.evidence_coverage).toEqual({ assessed_claims: 1, total_claims: 1, percentage: 100 }); expect(dimensions.model_agreement).toMatchObject({ agreeing_models: 2, total_models: 2 }); expect(dimensions.source_reliability.status).toBe('not_assessed'); expect(dimensions.source_independence.status).toBe('not_assessed'); expect(dimensions.recency.status).toBe('not_assessed'); expect(dimensions.contradictions).toMatchObject({ count: 0, severity: 'none' }); expect(dimensions.receipt_integrity.status).toBe('hash_verified'); expect(result.receipt.verification_dimensions).toEqual(dimensions); });
 it('reports material contradictions independently from model agreement', () => { const result = verifyEducation({ ...request, content: 'Both this statement and that statement are not true.' }); expect(result.education_result.verification_dimensions.contradictions).toMatchObject({ count: 1, severity: 'material' }); expect(result.education_result.verification_dimensions.model_agreement).toMatchObject({ agreeing_models: 1, total_models: 2 }); });
 it('aggregates claim scores', () => { expect(aggregateClaims([{ id: '1', text: 'x', classification: 'supported', confidence: 1, explanation: '', evidence: [], warnings: [] }])).toBe(1); });
});
