import { FormEvent, useEffect, useMemo, useState } from 'react';
import { fetchJson, postJson, requestJson } from './api';

type Role = 'owner' | 'admin' | 'member' | 'viewer';
type Org = { id: string; name: string; slug: string; plan: string; status: string; role: Role };
type Member = { userId: string; role: string; createdAt: string; user: { id: string; email?: string; externalId: string } };
type Task = { id: string; prompt: string; status: string; confidence?: number; verdict?: string; createdAt: string; requester: string };
type Key = { id: string; name: string; keyPrefix: string; scopes: string[]; createdAt: string; expiresAt?: string; revokedAt?: string; lastUsedAt?: string };
type Settings = { displayName?: string; logoUrl?: string; receiptPrefix?: string; publicReceiptsEnabled?: boolean; walletLoginEnabled?: boolean; educationFeaturesEnabled?: boolean; onchainAnchoringEnabled?: boolean; customBrandingEnabled?: boolean };
type Data = { organization: Org; members: Member[]; tasks: Task[]; keys: Key[]; settings: Settings; events: Array<{ id: string; action: string; createdAt: string }> };
const nav = [['overview', 'Dashboard'], ['receipts', 'Receipts'], ['projects', 'Projects'], ['keys', 'API Keys'], ['members', 'Members'], ['settings', 'Settings']] as const;
const canManage = (role: Role) => role === 'owner' || role === 'admin';
const date = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) : 'Never';
const initials = (name: string) => name.split(/[.@\s]/).filter(Boolean).slice(0, 2).map(x => x[0]).join('').toUpperCase();

function Empty({ title, copy, action }: { title: string; copy: string; action?: React.ReactNode }) { return <div className="empty"><div className="empty-icon">✦</div><h3>{title}</h3><p>{copy}</p>{action}</div>; }
function Dialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><button className="icon-button close" onClick={onClose} aria-label="Close dialog">×</button><h2>{title}</h2>{children}</section></div>; }

export default function App() {
  const [page, setPage] = useState('overview'); const [data, setData] = useState<Data | null>(null); const [orgs, setOrgs] = useState<Org[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [dialog, setDialog] = useState<null | 'key' | 'member' | 'secret'>(null); const [secret, setSecret] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [current, members, tasks, keys, settings, events, organizations] = await Promise.all([fetchJson<{ organization: Org; role: Role }>('/api/organizations/current'), fetchJson<{ members: Member[] }>('/api/organizations/current/members'), fetchJson<{ tasks: Task[] }>('/api/organizations/current/tasks'), fetchJson<{ keys: Key[] }>('/api/organizations/current/api-keys').catch(() => ({ keys: [] })), fetchJson<{ settings: Settings | null }>('/api/organizations/current/settings'), fetchJson<{ events: Data['events'] }>('/api/organizations/current/activity'), fetchJson<{ organizations: Org[] }>('/api/organizations/')]); setData({ organization: { ...current.organization, role: current.role }, members: members.members, tasks: tasks.tasks, keys: keys.keys, settings: settings.settings || {}, events: events.events }); setOrgs(organizations.organizations); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load your organization.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 3500); };
  if (loading) return <div className="loading-screen"><div className="brand-mark">M</div><p>Loading your organization…</p><div className="skeleton wide" /><div className="skeleton wide" /></div>;
  if (error || !data) return <main className="error-state"><div className="brand-mark">M</div><h1>We couldn’t load this workspace.</h1><p>{error || 'Your session may have expired.'}</p><button onClick={() => void load()}>Try again</button></main>;
  const { organization: org } = data;
  async function switchOrg(organizationId: string) { if (organizationId === org.id) return; try { const result = await postJson<{ requiresSessionRefresh: boolean }>('/api/organizations/switch', { organizationId }); if (result.requiresSessionRefresh) { notify('Organization verified. Refreshing your secure session…'); window.setTimeout(() => location.reload(), 650); } } catch (e) { notify(e instanceof Error ? e.message : 'Unable to switch organization.'); } }
  return <div className="saas-shell"><aside className="sidebar"><a className="sidebar-brand" href="/"><span className="brand-mark">M</span><span>MAMV</span></a><label className="org-switch"><span className="sr-only">Switch organization</span><select value={org.id} onChange={e => void switchOrg(e.target.value)}>{orgs.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><small>{org.plan} plan</small></label><nav>{nav.map(([id, label]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}>{label}</button>)}</nav><div className="sidebar-bottom"><span className="avatar">{initials(org.name)}</span><div><strong>{org.name}</strong><small>{org.role}</small></div></div></aside><main className="dashboard-main"><header className="dashboard-header"><div><p className="eyebrow">{page === 'overview' ? 'Organization overview' : page}</p><h1>{page === 'overview' ? `Welcome to ${data.settings.displayName || org.name}` : nav.find(([id]) => id === page)?.[1]}</h1></div><div className="header-actions"><span className={`status ${org.status.toLowerCase()}`}>{org.status.toLowerCase()}</span><button className="user-menu" aria-label="User menu"><span className="avatar">{initials(org.name)}</span>⌄</button></div></header>{page === 'overview' && <Overview data={data} go={setPage} />}{page === 'receipts' && <Receipts tasks={data.tasks} />}{page === 'projects' && <Projects />}{page === 'keys' && <Keys data={data} setDialog={setDialog} notify={notify} reload={load} />}{page === 'members' && <Members data={data} setDialog={setDialog} notify={notify} reload={load} />}{page === 'settings' && <SettingsPage data={data} notify={notify} reload={load} />}</main>{notice && <div className="toast" role="status">✓ {notice}</div>}{dialog === 'key' && <KeyDialog close={() => setDialog(null)} created={(key) => { setSecret(key); setDialog('secret'); void load(); }} />}{dialog === 'member' && <MemberDialog close={() => setDialog(null)} saved={() => { setDialog(null); notify('Member added to your organization.'); void load(); }} />}{dialog === 'secret' && <SecretDialog secret={secret} close={() => { setSecret(''); setDialog(null); }} />}</div>;
}
function Overview({ data, go }: { data: Data; go: (page: string) => void }) { const completed = data.tasks.filter(x => x.status === 'COMPLETED').length; return <><section className="stats-grid"><Stat label="Members" value={data.members.length} detail="People with access" /><Stat label="Verifications" value={completed} detail={`${data.tasks.length} total jobs`} /><Stat label="Receipts generated" value={data.tasks.length} detail="Organization scoped" /><Stat label="Active API keys" value={data.keys.filter(x => !x.revokedAt).length} detail="Secure server access" /></section><section className="dashboard-grid"><article className="panel span-2"><div className="panel-title"><div><h2>Recent receipts</h2><p>Verification work created in this organization.</p></div><button className="text-button" onClick={() => go('receipts')}>View all</button></div><TaskTable tasks={data.tasks.slice(0, 5)} /></article><article className="panel"><div className="panel-title"><div><h2>Organization status</h2><p>Your workspace is ready.</p></div></div><div className="readiness"><span className="status active">Active</span><h3>{data.organization.plan} plan</h3><p>Receipts and API keys are isolated to <strong>{data.settings.displayName || data.organization.name}</strong>.</p></div></article><article className="panel span-2"><div className="panel-title"><div><h2>Recent activity</h2><p>Changes made in your organization.</p></div></div>{data.events.length ? <ul className="activity">{data.events.slice(0, 6).map(event => <li key={event.id}><span>✓</span><div><strong>{event.action.replace(/_/g, ' ').toLowerCase()}</strong><small>{date(event.createdAt)}</small></div></li>)}</ul> : <Empty title="No activity yet" copy="Your organization activity will appear here." />}</article></section></>; }
function Stat({ label, value, detail }: { label: string; value: number; detail: string }) { return <article className="stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function TaskTable({ tasks }: { tasks: Task[] }) { if (!tasks.length) return <Empty title="No receipts yet" copy="Create your first verification to generate a trust receipt." />; return <div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Status</th><th>Confidence</th><th>Created</th></tr></thead><tbody>{tasks.map(task => <tr key={task.id}><td><strong>{task.prompt.slice(0, 54) || task.id}</strong><small>{task.id.slice(0, 8)}</small></td><td><span className="badge">{task.status.toLowerCase()}</span></td><td>{task.confidence === undefined ? '—' : `${Math.round(task.confidence * 100)}%`}</td><td>{date(task.createdAt)}</td></tr>)}</tbody></table></div>; }
function Receipts({ tasks }: { tasks: Task[] }) { const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const matches = useMemo(() => tasks.filter(t => (status === 'all' || t.status === status) && `${t.prompt} ${t.id}`.toLowerCase().includes(query.toLowerCase())), [tasks, query, status]); return <section className="panel"><div className="toolbar"><input aria-label="Search receipts" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search receipts…" /><select value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option>{[...new Set(tasks.map(x => x.status))].map(x => <option key={x} value={x}>{x}</option>)}</select></div>{matches.length ? <TaskTable tasks={matches} /> : <Empty title="No receipts found" copy="Try a different search or create your first verification." />}</section>; }
function Projects() { return <section className="panel"><Empty title="No projects yet" copy="Projects will group verification work within this organization. Create receipts today and organize them into projects as your workflow grows." /></section>; }
function Keys({ data, setDialog, notify, reload }: { data: Data; setDialog: (value: 'key') => void; notify: (x: string) => void; reload: () => Promise<void> }) { const manage = canManage(data.organization.role); async function revoke(key: Key) { if (!confirm(`Revoke ${key.name}? This cannot be undone.`)) return; try { await requestJson(`/api/organizations/current/api-keys/${key.id}`, 'DELETE'); notify('API key revoked.'); await reload(); } catch (e) { notify(e instanceof Error ? e.message : 'Unable to revoke key.'); } } return <section className="panel"><div className="panel-title"><div><h2>API keys</h2><p>Use keys for server-to-server access. Key values are shown only once.</p></div>{manage && <button onClick={() => setDialog('key')}>Generate API key</button>}</div>{data.keys.length ? <div className="table-wrap"><table><thead><tr><th>Name</th><th>Scopes</th><th>Last used</th><th>Expires</th><th /></tr></thead><tbody>{data.keys.map(key => <tr key={key.id}><td><strong>{key.name}</strong><small>{key.keyPrefix}••••••••</small></td><td>{key.scopes.join(', ')}</td><td>{date(key.lastUsedAt)}</td><td>{key.revokedAt ? <span className="badge muted">revoked</span> : date(key.expiresAt)}</td><td>{manage && !key.revokedAt && <button className="danger-link" onClick={() => void revoke(key)}>Revoke</button>}</td></tr>)}</tbody></table></div> : <Empty title="No API keys" copy="Generate your first API key to connect MAMV to your application." action={manage ? <button onClick={() => setDialog('key')}>Generate API key</button> : undefined} />}</section>; }
function Members({ data, setDialog, notify, reload }: { data: Data; setDialog: (value: 'member') => void; notify: (x: string) => void; reload: () => Promise<void> }) { const manage = canManage(data.organization.role); async function change(member: Member, role: string) { try { await requestJson(`/api/organizations/current/members/${member.userId}`, 'PATCH', { role }); notify('Member role updated.'); await reload(); } catch (e) { notify(e instanceof Error ? e.message : 'Unable to update role.'); } } async function remove(member: Member) { if (!confirm(`Remove ${member.user.email || member.user.externalId} from this organization?`)) return; try { await requestJson(`/api/organizations/current/members/${member.userId}`, 'DELETE'); notify('Member removed.'); await reload(); } catch (e) { notify(e instanceof Error ? e.message : 'Unable to remove member.'); } } return <section className="panel"><div className="panel-title"><div><h2>Members</h2><p>{data.members.length} people have access to this organization.</p></div>{manage && <button onClick={() => setDialog('member')}>Invite member</button>}</div>{data.members.length ? <div className="member-list">{data.members.map(member => <div className="member-row" key={member.userId}><span className="avatar large">{initials(member.user.email || member.user.externalId)}</span><div className="member-id"><strong>{member.user.email || member.user.externalId}</strong><small>Joined {date(member.createdAt)}</small></div>{manage ? <select aria-label={`Role for ${member.user.email || member.user.externalId}`} value={member.role.toLowerCase()} onChange={e => void change(member, e.target.value)}><option value="owner" disabled={data.organization.role !== 'owner'}>Owner</option><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option></select> : <span className="badge">{member.role.toLowerCase()}</span>}{manage && <button className="danger-link" onClick={() => void remove(member)}>Remove</button>}</div>)}</div> : <Empty title="No teammates" copy="Invite your first member to review receipts together." />}</section>; }
function SettingsPage({ data, notify, reload }: { data: Data; notify: (x: string) => void; reload: () => Promise<void> }) { const [saving, setSaving] = useState(false); const manage = canManage(data.organization.role); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { if (form.get('name') !== data.organization.name) await requestJson('/api/organizations/current', 'PATCH', { name: form.get('name') }); await requestJson('/api/organizations/current/settings', 'PATCH', { displayName: form.get('displayName'), logoUrl: form.get('logoUrl'), receiptPrefix: form.get('receiptPrefix'), publicReceiptsEnabled: form.get('publicReceiptsEnabled') === 'on', walletLoginEnabled: form.get('walletLoginEnabled') === 'on', educationFeaturesEnabled: form.get('educationFeaturesEnabled') === 'on', onchainAnchoringEnabled: form.get('onchainAnchoringEnabled') === 'on', customBrandingEnabled: form.get('customBrandingEnabled') === 'on' }); notify('Organization settings saved.'); await reload(); } catch (e) { notify(e instanceof Error ? e.message : 'Unable to save settings.'); } finally { setSaving(false); } } return <section className="panel settings"><div className="panel-title"><div><h2>Organization settings</h2><p>Control the name and branding customers see on your receipts.</p></div></div><form onSubmit={submit}><div className="form-grid"><label>Organization name<input name="name" disabled={!manage} defaultValue={data.organization.name} required maxLength={120} /></label><label>Display name<input name="displayName" disabled={!manage} defaultValue={data.settings.displayName || ''} maxLength={120} placeholder={data.organization.name} /></label><label>Logo URL<input name="logoUrl" disabled={!manage} type="url" defaultValue={data.settings.logoUrl || ''} placeholder="https://…" /></label><label>Receipt prefix<input name="receiptPrefix" disabled={!manage} defaultValue={data.settings.receiptPrefix || ''} maxLength={20} placeholder="MAMV" /></label></div><fieldset disabled={!manage}><legend>Features</legend><Check name="publicReceiptsEnabled" checked={data.settings.publicReceiptsEnabled} label="Allow public receipts" /><Check name="walletLoginEnabled" checked={data.settings.walletLoginEnabled} label="Enable wallet login" /><Check name="educationFeaturesEnabled" checked={data.settings.educationFeaturesEnabled} label="Enable education features" /><Check name="onchainAnchoringEnabled" checked={data.settings.onchainAnchoringEnabled} label="Enable on-chain anchoring" /><Check name="customBrandingEnabled" checked={data.settings.customBrandingEnabled} label="Enable custom branding" /></fieldset>{manage ? <button disabled={saving}>{saving ? 'Saving…' : 'Save changes'}</button> : <p className="help">You need an owner or admin role to edit these settings.</p>}</form></section>; }
function Check({ name, checked, label }: { name: string; checked?: boolean; label: string }) { return <label className="check"><input name={name} type="checkbox" defaultChecked={checked} />{label}</label>; }
function KeyDialog({ close, created }: { close: () => void; created: (key: string) => void }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await postJson<{ plaintextKey: string }>('/api/organizations/current/api-keys', { name: form.get('name'), scopes: form.getAll('scopes'), expiresAt: form.get('expiresAt') || undefined }); created(result.plaintextKey); } catch (e) { alert(e instanceof Error ? e.message : 'Unable to create API key.'); } } return <Dialog title="Generate API key" onClose={close}><p className="dialog-copy">Store the key in a password manager. It will never be shown again.</p><form onSubmit={submit}><label>Name<input name="name" required placeholder="Production integration" /></label><fieldset><legend>Scopes</legend><label className="check"><input name="scopes" type="checkbox" value="receipts:read" defaultChecked />Read receipts</label><label className="check"><input name="scopes" type="checkbox" value="verifications:create" defaultChecked />Create verifications</label></fieldset><label>Expiration (optional)<input name="expiresAt" type="date" /></label><button>Generate key</button></form></Dialog>; }
function MemberDialog({ close, saved }: { close: () => void; saved: () => void }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await postJson('/api/organizations/current/members', { email: form.get('email'), role: form.get('role') }); saved(); } catch (e) { alert(e instanceof Error ? e.message : 'Unable to invite member.'); } } return <Dialog title="Invite member" onClose={close}><p className="dialog-copy">Invite an existing MAMV account to collaborate in this organization.</p><form onSubmit={submit}><label>Email address<input name="email" type="email" required placeholder="teammate@company.com" /></label><label>Role<select name="role"><option value="member">Member</option><option value="viewer">Viewer</option><option value="admin">Admin</option></select></label><button>Send invitation</button></form></Dialog>; }
function SecretDialog({ secret, close }: { secret: string; close: () => void }) { const copy = async () => { await navigator.clipboard.writeText(secret); }; return <Dialog title="Copy your API key" onClose={close}><p className="warning">This is the only time you can view this key.</p><code className="secret">{secret}</code><div className="dialog-actions"><button className="secondary" onClick={() => void copy()}>Copy key</button><button onClick={close}>I’ve saved it</button></div></Dialog>; }
