import { FormEvent, useState } from 'react';
import JobDetail from './pages/JobDetail';
import JobDebug from './pages/JobDebug';
import { postJson } from './api';

type Dimensions = { evidence_coverage: { assessed_claims: number; total_claims: number; percentage: number }; source_reliability: { status: string; detail: string }; model_agreement: { agreeing_models: number; total_models: number; detail: string }; source_independence: { status: string; detail: string }; recency: { status: string; detail: string }; contradictions: { count: number; severity: string; detail: string }; receipt_integrity: { status: string; detail: string } };
type Result = { task_id: string; education_result: { support_level: string; confidence_score: number; summary: string; claims: Array<{ id: string; text: string; classification: string; confidence: number; explanation: string; warnings: string[] }>; verification_dimensions: Dimensions; warnings: string[]; review_questions: string[]; citation_review: { status: string; warnings: string[] }; model_agreement: { agreement_score: number; votes: Array<{ provider: string; model: string; vote: string; score: number }>; outliers: string[] }; limitations: string[]; demo_mode: boolean }; receipt: Record<string, unknown> };
const levels = ['elementary', 'middle-school', 'high-school', 'undergraduate', 'graduate', 'adult-learning'];
function EducationForm({ mode }: { mode: 'student_answer' | 'teacher_content' }) {
 const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
 async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setError(''); setLoading(true); try { setResult(await postJson<Result>('/v1/education/verify', { mode, question: String(form.get('question') || ''), content: String(form.get('content') || ''), subject: String(form.get('subject')), education_level: String(form.get('education_level')), content_type: String(form.get('content_type')), rubric: String(form.get('rubric') || ''), learning_objectives: String(form.get('objectives') || '').split('\n').filter(Boolean), provided_sources: String(form.get('sources') || '').split('\n').filter(Boolean).map(url => ({ url })), privacy_acknowledged: form.get('privacy_acknowledged') === 'on', options: { extract_claims: true, check_citations: true, include_model_votes: true } })); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to verify this material.'); } finally { setLoading(false); } }
 if (result) return <Results result={result} onBack={() => setResult(null)} />;
 const teacher = mode === 'teacher_content'; return <main className="education-page"><a href="/" className="back">← MAMV Education</a><header><p className="eyebrow">{teacher ? 'Teacher content review' : 'Student answer check'}</p><h1>{teacher ? 'Review teaching material' : 'Check an AI answer'}</h1><p>MAMV provides evidence and confidence signals. It does not guarantee truth, originality, fairness, or academic acceptability.</p></header><form className="education-form" onSubmit={submit}><div className="privacy" role="note"><strong>Privacy first.</strong> Do not submit names, IDs, emails, school names, grades, or any personal, confidential, or protected student information.</div>{teacher && <label>Material title<input name="question" maxLength={10000} /></label>} {!teacher && <label>Assignment question<textarea name="question" required maxLength={10000} /></label>}<label>{teacher ? 'Teaching material' : 'AI-generated answer'}<textarea name="content" required maxLength={50000} /></label><div className="form-grid"><label>Subject<input name="subject" required placeholder="e.g. earth-science" /></label><label>Education level<select name="education_level" defaultValue="middle-school">{levels.map(l => <option key={l}>{l}</option>)}</select></label><label>Content type<select name="content_type" defaultValue={teacher ? 'lesson-plan' : 'answer'}>{(teacher ? ['lesson-plan', 'study-guide', 'quiz', 'answer-key', 'explanation', 'handout'] : ['answer']).map(v => <option key={v}>{v}</option>)}</select></label></div><label>{teacher ? 'Learning objectives (one per line)' : 'Teacher instructions or rubric (optional)'}<textarea name={teacher ? 'objectives' : 'rubric'} /></label>{teacher && <label>Rubric (optional)<textarea name="rubric" /></label>}<label>Sources or citations (one URL per line, optional)<textarea name="sources" /></label><label className="check"><input name="privacy_acknowledged" type="checkbox" required /> I understand that I must not submit sensitive personal information.</label>{error && <p className="form-error" role="alert">{error}</p>}<button disabled={loading}>{loading ? 'Checking…' : teacher ? 'Review material' : 'Check answer'}</button></form></main>;
}
function DimensionCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="claim"><strong>{label}</strong><span>{value}</span><small>{detail}</small></article>; }
function Results({ result, onBack }: { result: Result; onBack: () => void }) { const r = result.education_result; const d = r.verification_dimensions; return <main className="education-page"><button className="back" onClick={onBack}>← Start another check</button>{r.demo_mode && <p className="demo-banner" role="status">Demo mode — deterministic simulated cross-checks, not live verification.</p>}<header><p className="eyebrow">Verification report</p><h1>{r.support_level.replace('_', ' ')}</h1><p>{r.summary}</p></header><section><h2>Verification dimensions</h2><p>Read each signal separately. Agreement between models is not evidence that a claim is correct.</p><div className="path-grid"><DimensionCard label="Evidence coverage" value={`${d.evidence_coverage.percentage}%`} detail={`${d.evidence_coverage.assessed_claims} of ${d.evidence_coverage.total_claims} extracted claims assessed.`} /><DimensionCard label="Source reliability" value={d.source_reliability.status.replace('_', ' ')} detail={d.source_reliability.detail} /><DimensionCard label="Model agreement" value={`${d.model_agreement.agreeing_models} of ${d.model_agreement.total_models}`} detail={d.model_agreement.detail} /><DimensionCard label="Source independence" value={d.source_independence.status.replace('_', ' ')} detail={d.source_independence.detail} /><DimensionCard label="Recency" value={d.recency.status.replace('_', ' ')} detail={d.recency.detail} /><DimensionCard label="Contradictions" value={`${d.contradictions.count} ${d.contradictions.severity}`} detail={d.contradictions.detail} /><DimensionCard label="Receipt integrity" value={d.receipt_integrity.status.replace('_', ' ')} detail={d.receipt_integrity.detail} /></div></section><section><h2>Important warnings</h2><ul>{[...r.warnings, ...r.limitations].map(x => <li key={x}>⚠ {x}</li>)}</ul></section><section><h2>Claim-by-claim results</h2>{r.claims.map(c => <article className="claim" key={c.id}><strong>● {c.classification.replace('_', ' ')}</strong><span>{Math.round(c.confidence * 100)}%</span><p>{c.text}</p><small>{c.explanation}</small></article>)}</section><section><h2>Citation review</h2><p>{r.citation_review.status.replace('_', ' ')}. {r.citation_review.warnings.join(' ')}</p></section><section><h2>Questions for further review</h2><ul>{r.review_questions.map(q => <li key={q}>{q}</li>)}</ul></section><section><h2>Education receipt</h2><p>Receipt ID: <code>{String(result.receipt.receipt_id)}</code></p><details><summary>Technical details</summary><pre>{JSON.stringify(result.receipt, null, 2)}</pre></details><button onClick={() => window.print()}>Print report</button></section></main> }

export default function App() { const parts = location.pathname.split('/').filter(Boolean); if (parts[0] === 'jobs' && parts[1]) return parts[2] === 'debug' ? <JobDebug jobId={parts[1]} /> : <JobDetail jobId={parts[1]} />; if (parts[0] === 'education' && parts[1] === 'student') return <EducationForm mode="student_answer" />; if (parts[0] === 'education' && parts[1] === 'teacher') return <EducationForm mode="teacher_content" />; return <main className="education-page"><header><p className="eyebrow">MAMV Education</p><h1>Evidence signals for AI-assisted learning</h1><p>MAMV helps students and educators review AI content. It does not guarantee that work is true, original, fair, or academically acceptable.</p></header><div className="path-grid"><a href="/education/student"><h2>Check an AI Answer</h2><p>Extract claims, see cross-check signals, citation warnings, and a portable receipt.</p></a><a href="/education/teacher"><h2>Review Teaching Material</h2><p>Review lesson plans, quizzes, handouts, answer keys, and explanations.</p></a></div><p className="demo-banner">Demo mode is enabled. Results are deterministic examples, not live verification.</p></main>; }
