/**
 * Inspectable allusion analysis. These records are concise summaries supplied
 * by a classifier, not hidden chain-of-thought and not evidence by themselves.
 */
export type AllusionType = 'historical' | 'literary' | 'religious' | 'mythological' | 'philosophical' | 'political' | 'cultural' | 'idiomatic' | 'conceptual' | 'quotation' | 'named_reference' | 'unknown';
export type AllusionStrategy = 'direct' | 'structured_reasoning' | 'self_consistency' | 'self_refine';
export type AllusionVerificationStatus = 'supported' | 'partially_supported' | 'unsupported' | 'ambiguous' | 'not_enough_information';

export interface AllusionDeliberation { strategy: AllusionStrategy; reasoning_summaries: string[]; assumptions: string[]; uncertainties: string[]; alternatives_considered: string[]; critiques: string[]; revisions: string[]; consensus_confidence?: number; model_stated_confidence?: number; limitations: string[]; }
export interface AllusionCandidate { allusion_id: string; text_span: string; start_offset?: number; end_offset?: number; type: AllusionType; possible_types?: AllusionType[]; explicitness: 'explicit' | 'implicit' | 'ambiguous'; proposed_source?: string; proposed_target_concept?: string; interpretation: string; literal_interpretation?: string; confidence: number; context_sensitive: boolean; alternative_interpretations: string[]; evidence_ids: string[]; warnings: string[]; deliberation?: AllusionDeliberation; }
export interface AllusionVerification { allusion_id: string; status: AllusionVerificationStatus; source_match?: string; target_concept_match?: string; evidence_ids: string[]; limitations: string[]; }
export interface AllusionAssessment { candidates: AllusionCandidate[]; verifications: AllusionVerification[]; overall_warnings: string[]; deliberation?: AllusionDeliberation; }
export interface AllusionOptions { enabled?: boolean; strategy?: AllusionStrategy; num_samples?: number; max_refine_iterations?: number; verify_sources?: boolean; include_philosophical_allusions?: boolean; minimum_detection_confidence?: number; expose_reasoning_summaries?: boolean; }
export const DEFAULT_ALLUSION_OPTIONS: Required<AllusionOptions> = Object.freeze({ enabled: false, strategy: 'direct', num_samples: 3, max_refine_iterations: 2, verify_sources: true, include_philosophical_allusions: true, minimum_detection_confidence: .6, expose_reasoning_summaries: true });

export function validateAllusionOptions(input: AllusionOptions = {}): string[] { const value = { ...DEFAULT_ALLUSION_OPTIONS, ...input }; const errors: string[] = []; if (!Number.isInteger(value.num_samples) || value.num_samples < 1 || value.num_samples > 5) errors.push('num_samples must be an integer between 1 and 5'); if (!Number.isInteger(value.max_refine_iterations) || value.max_refine_iterations < 0 || value.max_refine_iterations > 3) errors.push('max_refine_iterations must be an integer between 0 and 3'); if (!Number.isFinite(value.minimum_detection_confidence) || value.minimum_detection_confidence < 0 || value.minimum_detection_confidence > 1) errors.push('minimum_detection_confidence must be within [0,1]'); return errors; }
export function validateAllusionAssessment(assessment: AllusionAssessment): string[] { const errors: string[] = []; const ids = new Set<string>(); assessment.candidates.forEach((candidate, index) => { if (!candidate.allusion_id || ids.has(candidate.allusion_id)) errors.push(`candidates[${index}].allusion_id must be unique`); ids.add(candidate.allusion_id); if (!Number.isFinite(candidate.confidence) || candidate.confidence < 0 || candidate.confidence > 1) errors.push(`candidates[${index}].confidence must be within [0,1]`); }); return errors; }

type Pattern = Omit<AllusionCandidate, 'allusion_id' | 'text_span' | 'start_offset' | 'end_offset' | 'evidence_ids' | 'warnings' | 'deliberation'> & { pattern: RegExp; literal?: RegExp };
const PATTERNS: Pattern[] = [
  { pattern: /crossed the Rubicon/i, type: 'historical', explicitness: 'implicit', proposed_source: 'Julius Caesar crossing the Rubicon', proposed_target_concept: 'an irreversible commitment', interpretation: 'Uses a historical event as a figurative description of an irreversible decision.', literal_interpretation: 'A person physically crossed the Rubicon river.', confidence: .9, context_sensitive: true, alternative_interpretations: [] },
  { pattern: /Pandora[’']?s box/i, type: 'mythological', explicitness: 'implicit', proposed_source: 'Pandora myth', proposed_target_concept: 'cascading unintended consequences', interpretation: 'Invokes Pandora’s box to describe release of difficult-to-contain consequences.', literal_interpretation: 'A reference to an actual box associated with Pandora.', confidence: .9, context_sensitive: true, alternative_interpretations: [] },
  { pattern: /Trojan horse/i, literal: /(?:museum|wooden|displayed|artifact|replica).{0,60}Trojan horse|Trojan horse.{0,60}(?:museum|wooden|displayed|artifact|replica)/i, type: 'idiomatic', possible_types: ['idiomatic', 'mythological'], explicitness: 'ambiguous', proposed_source: 'Trojan Horse myth', proposed_target_concept: 'a concealed harmful purpose', interpretation: 'May use the Trojan horse story idiomatically to describe concealment or deception.', literal_interpretation: 'A wooden horse or an object representing the Trojan Horse.', confidence: .75, context_sensitive: true, alternative_interpretations: ['Literal historical or museum reference.'] },
  { pattern: /Big Brother/i, type: 'literary', explicitness: 'ambiguous', proposed_source: 'George Orwell, Nineteen Eighty-Four', proposed_target_concept: 'pervasive surveillance or authoritarian monitoring', interpretation: 'May allude to Orwell’s fictional surveillance regime.', literal_interpretation: 'A literal older sibling or a named organization.', confidence: .8, context_sensitive: true, alternative_interpretations: ['Literal family or product name.'] },
  { pattern: /David[- ]and[- ]Goliath/i, type: 'religious', explicitness: 'implicit', proposed_source: 'David and Goliath narrative', proposed_target_concept: 'an underdog confronting a much stronger opponent', interpretation: 'Uses the biblical narrative as an underdog comparison.', literal_interpretation: 'A discussion of the religious narrative itself.', confidence: .9, context_sensitive: true, alternative_interpretations: [] },
  { pattern: /universally communicable/i, type: 'philosophical', explicitness: 'ambiguous', proposed_source: 'Kantian account of judgment', proposed_target_concept: 'universal communicability of judgment', interpretation: 'Possible philosophical attribution; surrounding context is needed to distinguish Kant from generic language about communication.', literal_interpretation: 'A general requirement that judgments be communicated to everyone.', confidence: .55, context_sensitive: true, alternative_interpretations: ['Generic organizational communication requirement.'] },
];
export function isDirectQuotation(text: string): boolean { return /[“"][^”"]+[”"]/.test(text); }
export function isParaphraseCandidate(text: string): boolean { return /\b(?:as Orwell warned|in other words|echoing)\b/i.test(text); }
export function isLiteralUsage(text: string, candidate: Pick<Pattern, 'literal'>): boolean { return Boolean(candidate.literal?.test(text)); }
export function requiresContextForInterpretation(candidate: Pick<AllusionCandidate, 'context_sensitive'>): boolean { return candidate.context_sensitive; }
export function isLikelyAllusion(candidate: AllusionCandidate): boolean { return candidate.confidence >= .6 && !candidate.warnings.includes('literal_usage_more_plausible'); }
export function detectAllusions(input: { text: string; context?: string; claims?: Array<{ id: string; text?: string }>; provider?: unknown; options?: AllusionOptions }): AllusionCandidate[] {
  const options = { ...DEFAULT_ALLUSION_OPTIONS, ...input.options }; if (!options.enabled) return []; const text = `${input.context ? `${input.context}\n` : ''}${input.text}`; const offset = input.context ? input.context.length + 1 : 0;
  return PATTERNS.flatMap((pattern, index) => { if (pattern.type === 'philosophical' && !options.include_philosophical_allusions) return []; const match = pattern.pattern.exec(input.text); if (!match) return []; const literal = isLiteralUsage(text, pattern); const confidence = literal ? .1 : pattern.confidence; if (confidence < options.minimum_detection_confidence) return []; return [{ ...pattern, allusion_id: `allusion-${offset + (match.index ?? 0)}-${index + 1}`, text_span: match[0], start_offset: offset + (match.index ?? 0), end_offset: offset + (match.index ?? 0) + match[0].length, confidence, evidence_ids: [], warnings: literal ? ['literal_usage_more_plausible'] : [], alternative_interpretations: [...pattern.alternative_interpretations] }]; });
}
export function verifyAllusions(candidates: AllusionCandidate[], evidenceIds: Iterable<string> = []): AllusionVerification[] { const available = new Set(evidenceIds); return candidates.map(candidate => { const supported = candidate.evidence_ids.filter(id => available.has(id)); return { allusion_id: candidate.allusion_id, status: supported.length ? 'partially_supported' : 'not_enough_information', evidence_ids: supported, limitations: supported.length ? ['Available evidence has not independently established every contextual implication.'] : ['A classifier proposal and its confidence are not evidence; provide source or contextual evidence.'] }; }); }
export function consensusConfidence(candidates: AllusionCandidate[]): number { if (!candidates.length) return 0; const groups = new Map<string, number>(); for (const candidate of candidates) { const key = `${candidate.type}|${(candidate.proposed_source ?? '').toLowerCase()}|${(candidate.proposed_target_concept ?? '').toLowerCase()}`; groups.set(key, (groups.get(key) ?? 0) + 1); } return Math.max(...groups.values()) / candidates.length; }
