/**
 * Observable coherence and stability analysis.
 * This module analyzes only claims, evidence relations, context references, and
 * recorded verdicts. It does not inspect model internals or hidden reasoning.
 */
export type CoherencePhase = 'claim_extraction' | 'context_analysis' | 'evidence_review' | 'provider_verification' | 'critique' | 'revision' | 'final_review';
export type CoherenceTrigger = 'new_claim' | 'new_evidence' | 'context_change' | 'provider_vote' | 'critique' | 'revision' | 'policy_gate';
export type CoherenceEdgeType = 'supports' | 'contradicts' | 'qualifies' | 'depends_on' | 'interprets' | 'derived_from' | 'refers_to' | 'challenges';
export type CoherenceNodeType = 'claim' | 'evidence' | 'interpretation' | 'provider_judgment' | 'policy_rule' | 'verdict';

export interface CoherenceState { state_id: string; phase: CoherencePhase; sequence: number; claim_ids: string[]; evidence_ids: string[]; active_verdicts: string[]; unresolved_contradictions: string[]; unresolved_ambiguities: string[]; provider_disagreement: number; context_reference_ids: string[]; created_at: string; }
export interface CoherenceTransition { from_state_id: string; to_state_id: string; trigger: CoherenceTrigger; changed_claim_ids: string[]; changed_evidence_ids: string[]; verdict_changed: boolean; explanation: string; }
export interface FragmentationAssessment { fragmented: boolean; cluster_count: number; claim_clusters: Array<{ cluster_id: string; claim_ids: string[]; evidence_ids: string[] }>; disconnected_claim_ids: string[]; explanation: string; }
export interface IntegrationAssessment { integration_level: 'low' | 'moderate' | 'high'; integration_cost: number; supported_cross_links: number; unsupported_cross_links: number; overloaded: boolean; explanation: string; }
export interface PathDependenceAssessment { detected: boolean; sensitivity: number; influential_inputs: Array<{ type: 'earlier_context' | 'assumption' | 'evidence_order' | 'provider_order' | 'prior_verdict'; reference_id?: string; explanation: string }>; limitations: string[]; }
export interface BoundaryAssessment { near_boundary: boolean; sensitivity: number; perturbations: Array<{ change: string; original_verdict: string; perturbed_verdict: string; material_change: boolean }>; explanation: string; }
export interface ReorganizationEvent { event_id: string; trigger: 'critique' | 'new_evidence' | 'context_revision' | 'provider_challenge'; before_state_id: string; after_state_id: string; changed_claim_ids: string[]; changed_evidence_relations: string[]; verdict_changed: boolean; resolved_issue_ids: string[]; introduced_issue_ids: string[]; explanation: string; }
export interface CoherenceAssessment { version: string; states: CoherenceState[]; transitions: CoherenceTransition[]; coherence_score?: number; contradiction_density: number; fragmentation: FragmentationAssessment; integration: IntegrationAssessment; path_dependence: PathDependenceAssessment; boundary: BoundaryAssessment; reorganizations: ReorganizationEvent[]; convergence_stability?: number; warnings: string[]; limitations: string[]; }
/** Optional request configuration. Disabled by default to preserve direct verification behavior. */
export interface CoherenceConfig { enabled?: boolean; calculate_score?: boolean; analyze_fragmentation?: boolean; analyze_integration?: boolean; analyze_path_dependence?: boolean; analyze_boundaries?: boolean; max_paths?: number; max_perturbations?: number; integration_budget?: number; minimum_material_change?: number; include_in_receipt?: boolean; }
export interface CoherenceNode { id: string; type: CoherenceNodeType; }
export interface CoherenceEdge { id: string; from: string; to: string; type: CoherenceEdgeType; supported?: boolean; }
export interface CoherenceGraph { nodes: CoherenceNode[]; edges: CoherenceEdge[]; }
export interface CoherenceInput { claims: Array<{ id: string }>; evidence?: Array<{ id: string }>; relations?: Array<{ claim_id: string; evidence_id: string; relation_type: string }>; contradictions?: Array<{ claim_a_id: string; claim_b_id: string }>; context_reference_ids?: string[]; unresolved_ambiguities?: string[]; provider_disagreement?: number; }
export interface CoherenceOptions { integration_budget?: number; context_size?: number; interpretation_branches?: number; }
const clamp = (value: number) => Math.max(0, Math.min(1, value));

export function buildCoherenceGraph(input: CoherenceInput): CoherenceGraph {
 const nodes: CoherenceNode[] = [...input.claims.map(({id})=>({id,type:'claim' as const})), ...(input.evidence ?? []).map(({id})=>({id,type:'evidence' as const}))];
 const edges: CoherenceEdge[] = [];
 for (const relation of input.relations ?? []) edges.push({ id: `rel:${relation.claim_id}:${relation.evidence_id}`, from: relation.claim_id, to: relation.evidence_id, type: relation.relation_type === 'contradicts' ? 'contradicts' : relation.relation_type === 'qualifies' ? 'qualifies' : 'supports', supported: relation.relation_type === 'supports' });
 for (const contradiction of input.contradictions ?? []) edges.push({id:`contradiction:${contradiction.claim_a_id}:${contradiction.claim_b_id}`,from:contradiction.claim_a_id,to:contradiction.claim_b_id,type:'contradicts'});
 return { nodes, edges };
}
export function findContradictionCycles(graph: CoherenceGraph): CoherenceEdge[] { return graph.edges.filter(e => e.type === 'contradicts'); }
export function calculateContradictionDensity(graph: CoherenceGraph): number { const claims = graph.nodes.filter(n=>n.type==='claim').length; return claims < 2 ? 0 : clamp(findContradictionCycles(graph).length / (claims * (claims - 1) / 2)); }
export function findDisconnectedClusters(graph: CoherenceGraph): Array<{claim_ids:string[]; evidence_ids:string[]}> {
 const adjacency = new Map(graph.nodes.map(n=>[n.id,new Set<string>()])); for (const edge of graph.edges) { adjacency.get(edge.from)?.add(edge.to); adjacency.get(edge.to)?.add(edge.from); }
 const visited = new Set<string>(); const clusters: Array<{claim_ids:string[]; evidence_ids:string[]}> = [];
 for (const node of graph.nodes) if (!visited.has(node.id)) { const stack=[node.id], ids:string[]=[]; visited.add(node.id); while(stack.length){const id=stack.pop()!;ids.push(id);for(const next of adjacency.get(id)??[])if(!visited.has(next)){visited.add(next);stack.push(next);}} clusters.push({claim_ids:ids.filter(id=>graph.nodes.find(n=>n.id===id)?.type==='claim').sort(), evidence_ids:ids.filter(id=>graph.nodes.find(n=>n.id===id)?.type==='evidence').sort()}); }
 return clusters.sort((a,b)=>(a.claim_ids[0]??'').localeCompare(b.claim_ids[0]??''));
}
export function findUnsupportedBridges(graph: CoherenceGraph): CoherenceEdge[] { return graph.edges.filter(edge => ['depends_on','derived_from','interprets'].includes(edge.type) && !edge.supported); }
export function findOverloadedClaims(graph: CoherenceGraph, threshold=4): string[] { const counts=new Map<string,number>(); for(const edge of graph.edges) counts.set(edge.from,(counts.get(edge.from)??0)+1); return [...counts].filter(([id,count])=>graph.nodes.find(n=>n.id===id)?.type==='claim'&&count>threshold).map(([id])=>id).sort(); }
/** Bounded observable burden, not a measure of cognitive capacity. */
export function calculateIntegrationCost(graph: CoherenceGraph, options: CoherenceOptions = {}): number { const claims=graph.nodes.filter(n=>n.type==='claim').length, evidence=graph.nodes.filter(n=>n.type==='evidence').length, contradictions=findContradictionCycles(graph).length, unsupported=findUnsupportedBridges(graph).length; return clamp((claims + evidence + contradictions*2 + unsupported*2 + (options.context_size??0)/1000 + (options.interpretation_branches??0)) / 20); }
export function assessFragmentation(graph: CoherenceGraph): FragmentationAssessment { const clusters=findDisconnectedClusters(graph), disconnected=clusters.filter(c=>c.evidence_ids.length===0).flatMap(c=>c.claim_ids); return {fragmented:clusters.length>1,cluster_count:clusters.length,claim_clusters:clusters.map((c,i)=>({cluster_id:`cluster_${i+1}`, ...c})),disconnected_claim_ids:disconnected,explanation:clusters.length>1?'Claims form separate observable evidence clusters; this may be appropriate for independent claims.':'Claims and evidence form one connected observable cluster.'}; }
export function assessIntegration(graph: CoherenceGraph, options: CoherenceOptions = {}): IntegrationAssessment { const cost=calculateIntegrationCost(graph,options), unsupported=findUnsupportedBridges(graph).length, supported=graph.edges.filter(e=>e.supported&&['supports','depends_on','derived_from'].includes(e.type)).length, overloaded=cost>(options.integration_budget??.75); return {integration_level:cost<.34?'low':cost<.67?'moderate':'high',integration_cost:cost,supported_cross_links:supported,unsupported_cross_links:unsupported,overloaded,explanation:overloaded?'Verification context may exceed reliable integration capacity. Consider verifying claim groups separately.':'Integration burden is within the configured observable budget.'}; }
export function recommendVerificationMode(fragmentation: FragmentationAssessment, integration: IntegrationAssessment): 'verify_independently'|'verify_clusters_then_synthesize'|'verify_globally'|'insufficient_structure' { if(!fragmentation.claim_clusters.length)return'insufficient_structure'; if(fragmentation.fragmented&&integration.unsupported_cross_links)return'verify_clusters_then_synthesize'; if(fragmentation.fragmented)return'verify_independently'; return'verify_globally'; }
export function detectVerdictAttractors(paths: Array<{strategy:string; verdict:string; evidence_coverage?:number; contradictions?:number}>): Array<{normalized_verdict:string; occurrence_count:number; paths:string[]; convergence_ratio:number; evidence_consistency:number; unresolved_contradictions:number}> { const groups=new Map<string,typeof paths>(); for(const path of paths){const key=path.verdict.trim().toLowerCase();groups.set(key,[...(groups.get(key)??[]),path]);} return [...groups].map(([normalized_verdict,items])=>({normalized_verdict,occurrence_count:items.length,paths:items.map(i=>i.strategy).sort(),convergence_ratio:items.length/paths.length,evidence_consistency:items.length?items.reduce((n,p)=>n+(p.evidence_coverage??0),0)/items.length:0,unresolved_contradictions:items.reduce((n,p)=>n+(p.contradictions??0),0)})).sort((a,b)=>b.occurrence_count-a.occurrence_count||a.normalized_verdict.localeCompare(b.normalized_verdict)); }
export function analyzeCoherence(input: CoherenceInput, options: CoherenceOptions = {}): CoherenceAssessment { const graph=buildCoherenceGraph(input), fragmentation=assessFragmentation(graph), integration=assessIntegration(graph,options), density=calculateContradictionDensity(graph), ambiguity=(input.unresolved_ambiguities?.length??0); const score=clamp(1-density*.45-integration.unsupported_cross_links*.1-ambiguity*.05-(input.provider_disagreement??0)*.15); const warnings:string[]=[]; if(integration.overloaded)warnings.push('Verification context may exceed reliable integration capacity');if(fragmentation.fragmented)warnings.push('Answer combines weakly connected evidence clusters');if(integration.unsupported_cross_links)warnings.push('Global conclusion depends on unsupported cross-cluster links'); return {version:'1.0.0',states:[],transitions:[],coherence_score:score,contradiction_density:density,fragmentation,integration,path_dependence:{detected:false,sensitivity:0,influential_inputs:[],limitations:['No bounded alternative verification paths were supplied.']},boundary:{near_boundary:false,sensitivity:0,perturbations:[],explanation:'No plausible perturbations were supplied.'},reorganizations:[],warnings,limitations:['Coherence does not establish truth. Model agreement and convergence are not evidence. This assessment uses only observable verification records.']}; }
