import type { Verdict } from './verdicts';
import { verdictFromEvidence } from './verdicts';
import type { EvidenceRelationType, VerificationBoundary, VerificationBoundaryCode } from './receipt';
import { DEFAULT_GENERATION_POLICY, type PossibleWorld, type VerificationPossibilitySpace } from './possibilitySpace';

export type EvidenceRelationBasis = 'referential'|'inferential'|'contextual'|'conventional'|'indexical';
export interface WorldClaim { id: string; organization_id: string; verification_run_id: string; world_ids: string[]; original_text: string; normalized_text: string; source_span?: { start: number; end: number }; claim_type: 'factual'|'causal'|'predictive'|'comparative'|'interpretive'|'definition'|'quotation'|'other'; statement_type?: import('./pragmatics').StatementTypeClassification; content?: import('./pragmatics').ClaimContent; content_role?: 'literal'|'implied'|'hedge_disclosure'|'hedged_content'; assumptions: string[]; scope?: string | null; materiality_weight: number; parent_claim_id?: string | null; derived_from_claim_ids?: string[]; status: 'candidate'|'active'|'stabilized'|'split'|'merged'|'retyped'|'narrowed'|'widened'|'superseded'|'removed'; version: number; created_at: string; updated_at: string; }
export interface WorldEvidenceRelation { id: string; organization_id: string; verification_run_id: string; world_id: string; claim_id: string; evidence_id: string; relation_type: EvidenceRelationType; evidence_relation_basis: EvidenceRelationBasis | 'unspecified'; basis_detail?: string; rationale: string; weight?: number; source_independence_group?: string | null; provenance: { provider?: string; model?: string; reviewer_id?: string; method?: string }; created_at: string; }
export interface WorldAssessment { world_id: string; supported_claim_ids: string[]; contradicted_claim_ids: string[]; qualified_claim_ids: string[]; inconclusive_claim_ids: string[]; unresolved_claim_ids: string[]; independent_support_count: number; evidence_coverage: number; contradiction_severity: number; unresolved_material_claim_count: number; status: 'supported'|'plausible'|'weakened'|'rejected'|'unresolved'; explanation: string; }
export interface DistinctionCheck { distinguishable: boolean; surviving_world_ids: string[]; rejected_world_ids: string[]; equivalent_world_groups?: string[][]; unresolved_differences: Array<{ world_ids: string[]; difference: string; affected_claim_ids: string[] }>; next_information_needed: string[]; recommended_action: 'produce_verdict'|'retrieve_more_evidence'|'request_clarification'|'verify_multiple_worlds'|'unable_to_verify'; }
export interface StabilizedClaim { id: string; source_claim_ids: string[]; normalized_text: string; scope: string; assumptions: string[]; supporting_world_ids: string[]; contradicted_world_ids: string[]; unresolved_world_ids: string[]; evidence_relation_ids: string[]; status: 'supported'|'qualified'|'contradicted'|'mixed'|'unable_to_verify'; verdict_label?: 'Accurately quoted'|'Misquoted'|'Unable to verify quotation'; stabilization_reason: string; }
/**
 * An auditable observation from a distinct assessment of the same claim.  An
 * observation is a challenge only when it actually considered a material rival
 * scenario; repeated checks of the same scenario must not inflate rivalry.
 */
export interface ClaimRivalryObservation {
  receipt_id: string;
  assessed_at: string;
  program_fingerprint: string;
  considered_world_ids: string[];
  rival_world_ids: string[];
  outcome: 'survived' | 'contradicted' | 'unresolved';
  evidence_relation_ids: string[];
}

/**
 * A descriptive history of challenges and repeat assessments.  Counts are
 * traceability measurements, never a probability or a truth score.
 */
export interface ClaimRivalryHistory {
  claim_id: string;
  observation_count: number;
  re_verification_depth: number;
  genuine_rivalry_count: number;
  survived_rivalry_count: number;
  contradicted_rivalry_count: number;
  unresolved_rivalry_count: number;
  distinct_rival_world_ids: string[];
  distinct_program_fingerprints: string[];
  first_assessed_at?: string;
  last_assessed_at?: string;
  stability_status: 'not_yet_challenged' | 'survived_rivalry' | 'mixed_history' | 'contradicted' | 'unresolved';
  interpretation: string;
}
export interface PossibilityAwareVerdict { status: Verdict; selected_world_ids: string[]; unresolved_world_ids: string[]; explanation: string; metrics: { world_count: number; surviving_world_count: number; rejected_world_count: number; stabilized_claim_count: number; supported_claim_count: number; contradicted_claim_count: number; qualified_claim_count: number; unresolved_claim_count: number; independent_support_count: number; evidence_coverage: number }; alternatives_considered: Array<{ world_id: string; final_status: string; rationale: string }>; }

/** Build a claim's challenge record without translating its history into truth probability. */
export function claimRivalryHistory(claim_id: string, observations: ClaimRivalryObservation[]): ClaimRivalryHistory {
  const ordered = [...observations].sort((a, b) => a.assessed_at.localeCompare(b.assessed_at));
  const genuine = ordered.filter((observation) => observation.rival_world_ids.length > 0);
  const count = (outcome: ClaimRivalryObservation['outcome']) => genuine.filter((observation) => observation.outcome === outcome).length;
  const survived = count('survived'), contradicted = count('contradicted'), unresolved = count('unresolved');
  const stability_status: ClaimRivalryHistory['stability_status'] = !genuine.length
    ? 'not_yet_challenged'
    : contradicted > 0 && survived > 0 ? 'mixed_history'
    : contradicted > 0 ? 'contradicted'
    : unresolved > 0 ? 'unresolved'
    : 'survived_rivalry';
  return {
    claim_id, observation_count: ordered.length, re_verification_depth: Math.max(0, ordered.length - 1),
    genuine_rivalry_count: genuine.length, survived_rivalry_count: survived, contradicted_rivalry_count: contradicted,
    unresolved_rivalry_count: unresolved,
    distinct_rival_world_ids: [...new Set(genuine.flatMap((observation) => observation.rival_world_ids))].sort(),
    distinct_program_fingerprints: [...new Set(ordered.map((observation) => observation.program_fingerprint))].sort(),
    first_assessed_at: ordered[0]?.assessed_at, last_assessed_at: ordered.at(-1)?.assessed_at, stability_status,
    interpretation: `This history records ${genuine.length} genuine rival-scenario challenge${genuine.length === 1 ? '' : 's'} across ${ordered.length} assessment${ordered.length === 1 ? '' : 's'}; it is not a probability that the claim is true.`,
  };
}

export function validateWorlds(worlds: PossibleWorld[], policy = DEFAULT_GENERATION_POLICY): string[] { const e: string[] = []; if (!worlds.length) e.push('at least one world is required'); if (worlds.length > policy.max_worlds) e.push('world count exceeds generation_policy.max_worlds'); const ids = new Set<string>(); for (const w of worlds) { if (!w.id || ids.has(w.id)) e.push('world ids must be unique'); ids.add(w.id); if (!w.assumptions.length) e.push(`world ${w.id} requires an assumption`); if (policy.require_distinguishing_condition && !w.distinguishing_conditions.length) e.push(`world ${w.id} requires a distinguishing condition`); if (!w.material_difference.trim() && worlds.length > 1) e.push(`world ${w.id} requires a material difference`); } return e; }
export function mergeEquivalentWorlds(worlds: PossibleWorld[]): PossibleWorld[] { const seen = new Map<string, PossibleWorld>(); for (const w of worlds) { const key = `${w.world_type}:${w.interpretation.trim().toLowerCase()}:${[...w.assumptions].sort().join('|')}`; const old = seen.get(key); if (!old) seen.set(key, w); else old.distinguishing_conditions = [...new Set([...old.distinguishing_conditions, ...w.distinguishing_conditions])].sort(); } return [...seen.values()]; }
export function buildPossibilitySpace(params: { input_summary: string; organization_id: string; program_id: string; program_version: string; program_fingerprint: string; worlds: PossibleWorld[]; program?: Partial<VerificationPossibilitySpace>; created_at?: string }): VerificationPossibilitySpace {
  const policy = { ...DEFAULT_GENERATION_POLICY, ...params.program?.generation_policy }; const worlds = policy.merge_equivalent_worlds ? mergeEquivalentWorlds(params.worlds) : params.worlds;
  const errors = validateWorlds(worlds, policy); if (errors.length) throw new Error(`Invalid possibility space: ${errors.join('; ')}`);
  return { id: `possibility-${params.program_id}`, version: '1', interpretation_alternatives: worlds.map(w => ({ id: w.id, label: w.interpretation })), claim_types: params.program?.claim_types ?? ['factual','causal','predictive','comparative','interpretive','definition','quotation','other'], evidence_relation_types: params.program?.evidence_relation_types ?? ['supports','contradicts','qualifies','contextualizes','duplicates','derives_from','inconclusive'], assessment_outcomes: params.program?.assessment_outcomes ?? ['Supported','Contradicted','Mixed evidence','Unable to verify'], boundary_outcomes: params.program?.boundary_outcomes ?? ['RIVAL_WORLDS_INDISTINGUISHABLE'], schema_version: '1', input_summary: params.input_summary, worlds, allowed_claim_types: params.program?.allowed_claim_types, allowed_evidence_relation_types: params.program?.allowed_evidence_relation_types, allowed_verdicts: params.program?.allowed_verdicts, boundary_conditions: params.program?.boundary_conditions, evidence_requirements: params.program?.evidence_requirements, generation_policy: policy, program_id: params.program_id, program_version: params.program_version, program_fingerprint: params.program_fingerprint, created_at: params.created_at ?? new Date().toISOString() };
}
export function assessWorld(world: PossibleWorld, claims: WorldClaim[], relations: WorldEvidenceRelation[]): WorldAssessment { const cs = claims.filter(c => c.world_ids.includes(world.id) && c.status !== 'removed'); const rels = relations.filter(r => r.world_id === world.id); const ids = (t: EvidenceRelationType) => [...new Set(rels.filter(r => r.relation_type === t).map(r => r.claim_id))]; const supported = ids('supports'), contradicted = ids('contradicts'), qualified = ids('qualifies'), inconclusive = ids('inconclusive'); const covered = new Set([...supported,...contradicted,...qualified,...inconclusive]); const unresolved = cs.filter(c => !covered.has(c.id)).map(c => c.id); const groups = new Set(rels.filter(r => r.relation_type === 'supports' && r.source_independence_group && !r.provenance.model).map(r => r.source_independence_group!)); const coverage = cs.length ? covered.size / cs.length : 0; const severity = cs.length ? contradicted.length / cs.length : 1; const status: WorldAssessment['status'] = severity >= .5 ? 'rejected' : unresolved.length ? 'unresolved' : supported.length ? (qualified.length ? 'plausible' : 'supported') : 'weakened'; return { world_id: world.id, supported_claim_ids: supported, contradicted_claim_ids: contradicted, qualified_claim_ids: qualified, inconclusive_claim_ids: inconclusive, unresolved_claim_ids: unresolved, independent_support_count: groups.size, evidence_coverage: coverage, contradiction_severity: severity, unresolved_material_claim_count: cs.filter(c => unresolved.includes(c.id) && c.materiality_weight >= .5).length, status, explanation: `${supported.length} supported, ${contradicted.length} contradicted, and ${unresolved.length} unresolved claims.` }; }
export const assessAllWorlds = (worlds: PossibleWorld[], claims: WorldClaim[], relations: WorldEvidenceRelation[]) => worlds.map(w => assessWorld(w, claims, relations));
export function evaluateWorldDistinction(worlds: PossibleWorld[], claims: WorldClaim[], assessments: WorldAssessment[]): DistinctionCheck { const rejected = assessments.filter(a => a.status === 'rejected').map(a => a.world_id); const survivors = assessments.filter(a => a.status !== 'rejected').map(a => a.world_id); const unresolved = assessments.filter(a => a.unresolved_material_claim_count > 0); if (!survivors.length) return { distinguishable: false, surviving_world_ids: [], rejected_world_ids: rejected, unresolved_differences: [], next_information_needed: ['Evidence for a materially different interpretation.'], recommended_action: 'unable_to_verify' }; if (survivors.length === 1 && !unresolved.length) return { distinguishable: true, surviving_world_ids: survivors, rejected_world_ids: rejected, unresolved_differences: [], next_information_needed: [], recommended_action: 'produce_verdict' }; const differences = survivors.map(id => ({ world_ids: [id], difference: worlds.find(w => w.id === id)?.material_difference ?? 'Unresolved interpretation', affected_claim_ids: claims.filter(c => c.world_ids.includes(id)).map(c => c.id) })); return { distinguishable: false, surviving_world_ids: survivors, rejected_world_ids: rejected, unresolved_differences: differences, next_information_needed: worlds.filter(w => survivors.includes(w.id)).flatMap(w => w.distinguishing_conditions), recommended_action: unresolved.length ? 'retrieve_more_evidence' : 'verify_multiple_worlds' }; }
export function stabilizeClaims(claims: WorldClaim[], relations: WorldEvidenceRelation[], assessments: WorldAssessment[], distinction: DistinctionCheck): StabilizedClaim[] { return claims.filter(c => c.status === 'active' && !!c.scope && c.assumptions.length && c.world_ids.some(id => distinction.surviving_world_ids.includes(id))).map(c => { const rs = relations.filter(r => r.claim_id === c.id); const support = rs.filter(r => r.relation_type === 'supports').map(r => r.world_id); const contradict = rs.filter(r => r.relation_type === 'contradicts').map(r => r.world_id); const unresolved = c.world_ids.filter(id => assessments.find(a => a.world_id === id)?.unresolved_claim_ids.includes(c.id)); const type = c.statement_type?.statement_type; const cannotLiteralVerdict = type === 'hypothetical' || type === 'rhetorical_question' || type === 'figurative' || type === 'sincerity_unclear'; const status: StabilizedClaim['status'] = cannotLiteralVerdict ? 'unable_to_verify' : contradict.length ? (support.length ? 'mixed' : 'contradicted') : rs.some(r => r.relation_type === 'qualifies') ? 'qualified' : support.length ? 'supported' : 'unable_to_verify'; const verdict_label = type === 'quotation' ? (support.length ? 'Accurately quoted' : contradict.length ? 'Misquoted' : 'Unable to verify quotation') : undefined; return { id: `stabilized-${c.id}`, source_claim_ids: [c.id], normalized_text: c.normalized_text, scope: c.scope!, assumptions: [...c.assumptions], supporting_world_ids: [...new Set(support)], contradicted_world_ids: [...new Set(contradict)], unresolved_world_ids: unresolved, evidence_relation_ids: rs.map(r => r.id), status, verdict_label, stabilization_reason: cannotLiteralVerdict ? `${type.replace(/_/g, ' ')} is not verified as a direct factual claim.` : type === 'quotation' ? 'Verdict concerns quotation accuracy, not truth of quoted content.' : 'Claim has explicit scope and assumptions and was compared across surviving scenarios.' }; }); }
export function possibilityAwareVerdict(space: VerificationPossibilitySpace, assessments: WorldAssessment[], distinction: DistinctionCheck, claims: StabilizedClaim[]): PossibilityAwareVerdict { const coverage = assessments.length ? assessments.reduce((n,a) => n+a.evidence_coverage,0)/assessments.length : 0; const independent = assessments.reduce((n,a) => n+a.independent_support_count,0); const status = distinction.recommended_action === 'unable_to_verify' || distinction.recommended_action === 'retrieve_more_evidence' ? 'Unable to verify' : verdictFromEvidence({ evidenceCoverage: coverage, supportedClaimRatio: claims.length ? claims.filter(c=>c.status==='supported').length/claims.length : 0, contradictedClaimRatio: claims.length ? claims.filter(c=>c.status==='contradicted').length/claims.length : 0, independentSupportCount: independent, hasMaterialContradiction: claims.some(c=>c.status==='contradicted'||c.status==='mixed') }); const selected = distinction.surviving_world_ids.filter(id => assessments.find(a=>a.world_id===id)?.status === 'supported'); return { status, selected_world_ids: selected, unresolved_world_ids: distinction.surviving_world_ids.filter(id=>!selected.includes(id)), explanation: `Assessment considered ${space.worlds?.length ?? 0} scenarios using claim-evidence relationships.`, metrics: { world_count: space.worlds?.length ?? 0, surviving_world_count: distinction.surviving_world_ids.length, rejected_world_count: distinction.rejected_world_ids.length, stabilized_claim_count: claims.length, supported_claim_count: claims.filter(c=>c.status==='supported').length, contradicted_claim_count: claims.filter(c=>c.status==='contradicted').length, qualified_claim_count: claims.filter(c=>c.status==='qualified').length, unresolved_claim_count: claims.filter(c=>c.status==='unable_to_verify').length, independent_support_count: independent, evidence_coverage: coverage }, alternatives_considered: assessments.map(a=>({ world_id:a.world_id, final_status:a.status, rationale:a.explanation })) }; }
export function boundariesForDistinction(check: DistinctionCheck): VerificationBoundary[] { if (check.distinguishable) return []; const code: VerificationBoundaryCode = check.recommended_action === 'unable_to_verify' ? 'POSSIBILITY_SPACE_INCOMPLETE' : 'RIVAL_WORLDS_INDISTINGUISHABLE'; return [{ code, affected_claim_ids: check.unresolved_differences.flatMap(d=>d.affected_claim_ids), explanation: 'Rival scenarios could not be distinguished with the reviewed evidence.', required_next_information: check.next_information_needed }]; }
